name: nuclino-mcp
region: fra
services:
- name: nuclino-mcp
  source_dir: /
  github:
    branch: main
    deploy_on_push: true
    repo: blubblub/nuclino-mcp
  instance_count: 1
  routes:
  - path: /
#domains:
#- domain: wiki.mcp.blubblub.org
#  type: PRIMARY
